import os
import json
import asyncio
from contextlib import asynccontextmanager
from typing import Optional, List, Dict, Any
from fastapi import FastAPI, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from rag_service import RAGService

# Initialize RAG service singleton
rag_service = RAGService()


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Function:
        Manages the application lifecycle, executing startup health checks against
        local Ollama daemons and ChromaDB persistence, followed by graceful resource release.

    Input:
        app (FastAPI): The root FastAPI application instance.

    Output:
        None: Yields control to the application during runtime.
    """
    # Startup validation
    try:
        count = rag_service.collection.count()
        print(f"[AI Engine Startup] ChromaDB connected. Total active chunks: {count}")
        models = rag_service.ollama_client.list()
        print(f"[AI Engine Startup] Ollama connected. Available models verified.")
    except Exception as e:
        print(f"[AI Engine Startup Warning] Component check warning: {e}")
    yield
    print("[AI Engine Shutdown] Service gracefully shutting down.")


app = FastAPI(
    title="Enterprise Local RAG Chatbot - AI Engine",
    description="Air-gapped vector search and LLM inference engine using ChromaDB and Ollama.",
    version="2.0.0",
    lifespan=lifespan
)

# Cross-Origin Resource Sharing for internal microservices
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


class DocumentIngestPayload(BaseModel):
    fileName: Optional[str] = Field(None, description="Human-readable filename of the SOP document")
    absolutePath: str = Field(..., description="Absolute filesystem path to the target PDF file")
    fileSizeKb: Optional[int] = Field(0, description="File size measured in kilobytes")
    lastModified: Optional[str] = Field(None, description="ISO-8601 timestamp of last file modification")


class ChatRequest(BaseModel):
    query: str = Field(..., min_length=1, description="The operational SOP inquiry submitted by the employee")
    top_k: Optional[int] = Field(4, ge=1, le=10, description="Maximum number of context chunks to retrieve")


class Citation(BaseModel):
    document: str = Field(..., description="Source SOP document name")
    page: int = Field(..., description="1-indexed document page number")
    section: str = Field(..., description="Extracted section heading or operational context")
    snippet: str = Field(..., description="Extracted text chunk excerpt")
    distance: float = Field(..., description="Cosine distance metric from query vector")


class ChatResponse(BaseModel):
    answer: str = Field(..., description="Grounded response generated by local LLM")
    citations: List[Citation] = Field(default_factory=list, description="List of source citations")
    context_count: int = Field(..., description="Number of context segments incorporated into prompt")


@app.get("/", tags=["System"])
async def root() -> Dict[str, Any]:
    """
    Function:
        Provides high-level system identification, runtime operational status,
        and configured local AI model bindings.

    Input:
        None: Handled via standard HTTP GET.

    Output:
        Dict[str, Any]: Metadata payload indicating microservice identity and models.
    """
    return {
        "status": "online",
        "service": "Enterprise Local RAG AI Engine",
        "models": {
            "chat": "llama3.1",
            "embeddings": "nomic-embed-text"
        },
        "engine": "FastAPI + ChromaDB + Ollama"
    }


@app.get("/api/health", tags=["System"])
async def health_check() -> Dict[str, Any]:
    """
    Function:
        Executes real-time diagnostics on ChromaDB persistence and Ollama daemon responsiveness.
        Provides telemetry metrics utilized by the Java Orchestrator and Streamlit UI.

    Input:
        None: Handled via standard HTTP GET.

    Output:
        Dict[str, Any]: Health diagnostic metrics containing ChromaDB chunk count
                        and Ollama daemon reachability status.
    """
    try:
        chunk_count = rag_service.collection.count()
        ollama_status = "healthy"
        try:
            rag_service.ollama_client.list()
        except Exception:
            ollama_status = "unreachable"

        return {
            "status": "healthy" if ollama_status == "healthy" else "degraded",
            "chroma_total_chunks": chunk_count,
            "ollama_status": ollama_status
        }
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Health probe failure: {str(e)}"
        )


@app.post("/api/documents/ingest", tags=["Ingestion"])
async def ingest_document(payload: DocumentIngestPayload) -> Dict[str, Any]:
    """
    Function:
        Asynchronously delegates PDF text extraction, semantic chunking, embedding generation,
        and ChromaDB storage to a background worker thread. Guarantees non-blocking execution
        for the orchestrator while processing heavy multi-page documents.

    Input:
        payload (DocumentIngestPayload): JSON payload specifying absolute file path and metadata.

    Output:
        Dict[str, Any]: Operational receipt confirming total pages and indexed chunk count.
                        Raises HTTP 404 if file does not exist, or HTTP 500 on parser error.
    """
    if not os.path.exists(payload.absolutePath):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Requested document not found on host filesystem: {payload.absolutePath}"
        )

    try:
        # Offload synchronous PDF vectorization to thread pool to preserve event loop latency
        result = await asyncio.to_thread(
            rag_service.ingest_pdf,
            file_path=payload.absolutePath,
            file_name=payload.fileName
        )
        return result
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Ingestion pipeline failure: {str(e)}"
        )


@app.post("/api/chat", response_model=ChatResponse, tags=["Inference"])
async def chat(request: ChatRequest) -> ChatResponse:
    """
    Function:
        Asynchronously handles employee natural-language inquiries by coordinating vector
        retrieval, relevance filtering, and local Llama 3.1 inference within a worker thread.
        Enforces strict hallucination guardrails.

    Input:
        request (ChatRequest): Incoming query payload containing user prompt and top_k parameter.

    Output:
        ChatResponse: Structured Pydantic response containing the verified answer,
                      individual citation objects, and context metrics.
    """
    cleaned_query = request.query.strip()
    if not cleaned_query:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Query string cannot be blank."
        )

    try:
        # Execute query retrieval and Ollama inference asynchronously
        result = await asyncio.to_thread(
            rag_service.query,
            user_query=cleaned_query,
            top_k=request.top_k or 4
        )
        return ChatResponse(**result)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"RAG query execution error: {str(e)}"
        )


@app.post("/api/chat/stream", tags=["Inference"])
async def chat_stream(request: ChatRequest):
    """
    Function:
        Streams token generation events in real-time using ndjson format.
        Yields citation headers, real-time token chunks, and final completion payload.

    Input:
        request (ChatRequest): Query string and top_k parameters.

    Output:
        StreamingResponse: application/x-ndjson stream of JSON objects.
    """
    cleaned_query = request.query.strip()
    if not cleaned_query:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Query string cannot be blank."
        )

    def event_stream():
        for event in rag_service.query_stream(user_query=cleaned_query, top_k=request.top_k or 4):
            yield json.dumps(event) + "\n"

    return StreamingResponse(
        event_stream(),
        media_type="application/x-ndjson"
    )


@app.get("/api/documents", tags=["Ingestion"])
async def list_documents() -> List[Dict[str, Any]]:
    """
    Function:
        Queries the persistent ChromaDB collection to produce an aggregated index
        of all currently ingested SOP manuals, their file paths, and chunk counts.

    Input:
        None: Handled via standard HTTP GET.

    Output:
        List[Dict[str, Any]]: Array of document metadata summaries.
    """
    try:
        return await asyncio.to_thread(rag_service.list_indexed_documents)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to query document catalog: {str(e)}"
        )


if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=False)
